export interface CuentaEstandar {
  codigo: string;
  nombre: string;
  nivel: number;
  tipo: 'ACTIVO' | 'PASIVO' | 'PATRIMONIO' | 'INGRESOS' | 'GASTOS';
  esAuxiliar: boolean;
  permiteMovimiento: boolean;
  cuentaPadreCodigo: string | null;
}

export const PLAN_CUENTAS_ESTANDAR: CuentaEstandar[] = [
  { codigo: '1', nombre: 'ACTIVO', nivel: 1, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: null },
  { codigo: '1.1', nombre: 'ACTIVO CORRIENTE', nivel: 2, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '1' },
  { codigo: '1.1.01', nombre: 'EFECTIVO Y EQUIVALENTES AL EFECTIVO', nivel: 3, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '1.1' },
  { codigo: '1.1.01.01', nombre: 'Caja', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.1.01' },
  { codigo: '1.1.01.02', nombre: 'Bancos', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.1.01' },
  { codigo: '1.1.01.03', nombre: 'Cuentas de ahorro', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.1.01' },
  { codigo: '1.1.02', nombre: 'ACTIVOS FINANCIEROS', nivel: 3, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '1.1' },
  { codigo: '1.1.02.01', nombre: 'Clientes', nivel: 4, tipo: 'ACTIVO', esAuxiliar: true, permiteMovimiento: true, cuentaPadreCodigo: '1.1.02' },
  { codigo: '1.1.02.02', nombre: 'Cuentas por cobrar', nivel: 4, tipo: 'ACTIVO', esAuxiliar: true, permiteMovimiento: true, cuentaPadreCodigo: '1.1.02' },
  { codigo: '1.1.02.03', nombre: '(-) Provision cuentas incobrables', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.1.02' },
  { codigo: '1.1.03', nombre: 'INVENTARIOS', nivel: 3, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '1.1' },
  { codigo: '1.1.03.01', nombre: 'Inventario de mercaderia', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.1.03' },
  { codigo: '1.1.03.02', nombre: 'Inventario de materias primas', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.1.03' },
  { codigo: '1.1.03.03', nombre: 'Inventario de productos terminados', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.1.03' },
  { codigo: '1.1.03.04', nombre: 'Inventario de suministros', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.1.03' },
  { codigo: '1.1.04', nombre: 'ACTIVOS POR IMPUESTOS', nivel: 3, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '1.1' },
  { codigo: '1.1.04.01', nombre: 'IVA Credito fiscal', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.1.04' },
  { codigo: '1.1.04.02', nombre: 'Anticipo impuesto a la renta', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.1.04' },
  { codigo: '1.1.04.03', nombre: 'Credito tributario IVA', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.1.04' },
  { codigo: '1.1.05', nombre: 'OTROS ACTIVOS CORRIENTES', nivel: 3, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '1.1' },
  { codigo: '1.1.05.01', nombre: 'Gastos pagados por anticipado', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.1.05' },
  { codigo: '1.1.05.02', nombre: 'Anticipos a proveedores', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.1.05' },
  { codigo: '1.1.05.03', nombre: 'Documentos por cobrar', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.1.05' },
  { codigo: '1.2', nombre: 'ACTIVO NO CORRIENTE', nivel: 2, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '1' },
  { codigo: '1.2.01', nombre: 'PROPIEDAD PLANTA Y EQUIPO', nivel: 3, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '1.2' },
  { codigo: '1.2.01.01', nombre: 'Terrenos', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.2.01' },
  { codigo: '1.2.01.02', nombre: 'Edificios', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.2.01' },
  { codigo: '1.2.01.03', nombre: 'Maquinaria y equipo', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.2.01' },
  { codigo: '1.2.01.04', nombre: 'Equipo de computacion', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.2.01' },
  { codigo: '1.2.01.05', nombre: '(-) Depreciacion acumulada', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.2.01' },
  { codigo: '1.2.01.06', nombre: 'Muebles y enseres', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.2.01' },
  { codigo: '1.2.01.07', nombre: 'Vehiculos', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.2.01' },
  { codigo: '1.2.01.08', nombre: 'Equipo de oficina', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.2.01' },
  { codigo: '1.2.02', nombre: 'INTANGIBLES', nivel: 3, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '1.2' },
  { codigo: '1.2.02.01', nombre: 'Software y licencias', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.2.02' },
  { codigo: '1.2.02.02', nombre: 'Patentes y marcas', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.2.02' },
  { codigo: '1.2.02.03', nombre: '(-) Amortizacion acumulada', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.2.02' },
  { codigo: '1.2.03', nombre: 'OTROS ACTIVOS NO CORRIENTES', nivel: 3, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '1.2' },
  { codigo: '1.2.03.01', nombre: 'Inversiones permanentes', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.2.03' },
  { codigo: '1.2.03.02', nombre: 'Cuentas por cobrar a largo plazo', nivel: 4, tipo: 'ACTIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '1.2.03' },
  { codigo: '2', nombre: 'PASIVO', nivel: 1, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: null },
  { codigo: '2.1', nombre: 'PASIVO CORRIENTE', nivel: 2, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '2' },
  { codigo: '2.1.01', nombre: 'CUENTAS POR PAGAR', nivel: 3, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '2.1' },
  { codigo: '2.1.01.01', nombre: 'Proveedores', nivel: 4, tipo: 'PASIVO', esAuxiliar: true, permiteMovimiento: true, cuentaPadreCodigo: '2.1.01' },
  { codigo: '2.1.01.02', nombre: 'Cuentas por pagar', nivel: 4, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '2.1.01' },
  { codigo: '2.1.01.03', nombre: 'Documentos por pagar', nivel: 4, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '2.1.01' },
  { codigo: '2.1.02', nombre: 'OBLIGACIONES LABORALES', nivel: 3, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '2.1' },
  { codigo: '2.1.02.01', nombre: 'Sueldos por pagar', nivel: 4, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '2.1.02' },
  { codigo: '2.1.02.02', nombre: 'Decimo tercer sueldo', nivel: 4, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '2.1.02' },
  { codigo: '2.1.02.03', nombre: 'Decimo cuarto sueldo', nivel: 4, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '2.1.02' },
  { codigo: '2.1.02.04', nombre: 'Fondos de reserva por pagar', nivel: 4, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '2.1.02' },
  { codigo: '2.1.02.05', nombre: 'Aportes IESS por pagar', nivel: 4, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '2.1.02' },
  { codigo: '2.1.02.06', nombre: 'Beneficios sociales por pagar', nivel: 4, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '2.1.02' },
  { codigo: '2.1.03', nombre: 'OBLIGACIONES TRIBUTARIAS', nivel: 3, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '2.1' },
  { codigo: '2.1.03.01', nombre: 'IVA Debito fiscal', nivel: 4, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '2.1.03' },
  { codigo: '2.1.03.02', nombre: 'Retencion IVA por pagar', nivel: 4, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '2.1.03' },
  { codigo: '2.1.03.03', nombre: 'Retencion Renta por pagar', nivel: 4, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '2.1.03' },
  { codigo: '2.1.03.04', nombre: 'Impuesto a la renta por pagar', nivel: 4, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '2.1.03' },
  { codigo: '2.1.03.05', nombre: 'ICE por pagar', nivel: 4, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '2.1.03' },
  { codigo: '2.1.04', nombre: 'OTROS PASIVOS CORRIENTES', nivel: 3, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '2.1' },
  { codigo: '2.1.04.01', nombre: 'Prestamos bancarios corto plazo', nivel: 4, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '2.1.04' },
  { codigo: '2.1.04.02', nombre: 'Anticipos de clientes', nivel: 4, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '2.1.04' },
  { codigo: '2.1.04.03', nombre: 'Dividendos por pagar', nivel: 4, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '2.1.04' },
  { codigo: '2.2', nombre: 'PASIVO NO CORRIENTE', nivel: 2, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '2' },
  { codigo: '2.2.01', nombre: 'OBLIGACIONES A LARGO PLAZO', nivel: 3, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '2.2' },
  { codigo: '2.2.01.01', nombre: 'Prestamos bancarios largo plazo', nivel: 4, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '2.2.01' },
  { codigo: '2.2.01.02', nombre: 'Cuentas por pagar largo plazo', nivel: 4, tipo: 'PASIVO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '2.2.01' },
  { codigo: '3', nombre: 'PATRIMONIO', nivel: 1, tipo: 'PATRIMONIO', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: null },
  { codigo: '3.1', nombre: 'CAPITAL', nivel: 2, tipo: 'PATRIMONIO', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '3' },
  { codigo: '3.1.01', nombre: 'Capital social', nivel: 3, tipo: 'PATRIMONIO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '3.1' },
  { codigo: '3.1.02', nombre: 'Aportes de accionistas', nivel: 3, tipo: 'PATRIMONIO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '3.1' },
  { codigo: '3.2', nombre: 'RESERVAS', nivel: 2, tipo: 'PATRIMONIO', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '3' },
  { codigo: '3.2.01', nombre: 'Reserva legal', nivel: 3, tipo: 'PATRIMONIO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '3.2' },
  { codigo: '3.2.02', nombre: 'Reserva estatutaria', nivel: 3, tipo: 'PATRIMONIO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '3.2' },
  { codigo: '3.3', nombre: 'RESULTADOS', nivel: 2, tipo: 'PATRIMONIO', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '3' },
  { codigo: '3.3.01', nombre: 'Utilidad del ejercicio', nivel: 3, tipo: 'PATRIMONIO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '3.3' },
  { codigo: '3.3.02', nombre: '(-) Perdida del ejercicio', nivel: 3, tipo: 'PATRIMONIO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '3.3' },
  { codigo: '3.3.03', nombre: 'Utilidades retenidas', nivel: 3, tipo: 'PATRIMONIO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '3.3' },
  { codigo: '3.3.04', nombre: 'Resultados acumulados', nivel: 3, tipo: 'PATRIMONIO', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '3.3' },
  { codigo: '4', nombre: 'INGRESOS', nivel: 1, tipo: 'INGRESOS', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: null },
  { codigo: '4.1', nombre: 'INGRESOS OPERACIONALES', nivel: 2, tipo: 'INGRESOS', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '4' },
  { codigo: '4.1.01', nombre: 'Ventas', nivel: 3, tipo: 'INGRESOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '4.1' },
  { codigo: '4.1.01.01', nombre: 'Ventas 12%', nivel: 4, tipo: 'INGRESOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '4.1.01' },
  { codigo: '4.1.01.02', nombre: 'Ventas 14%', nivel: 4, tipo: 'INGRESOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '4.1.01' },
  { codigo: '4.1.01.03', nombre: 'Ventas 15%', nivel: 4, tipo: 'INGRESOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '4.1.01' },
  { codigo: '4.1.01.04', nombre: 'Ventas 0%', nivel: 4, tipo: 'INGRESOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '4.1.01' },
  { codigo: '4.1.01.05', nombre: 'Exportaciones', nivel: 4, tipo: 'INGRESOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '4.1.01' },
  { codigo: '4.1.02', nombre: 'Devolucion en ventas', nivel: 3, tipo: 'INGRESOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '4.1' },
  { codigo: '4.1.03', nombre: 'Servicios prestados', nivel: 3, tipo: 'INGRESOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '4.1' },
  { codigo: '4.2', nombre: 'INGRESOS NO OPERACIONALES', nivel: 2, tipo: 'INGRESOS', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '4' },
  { codigo: '4.2.01', nombre: 'Ingresos financieros', nivel: 3, tipo: 'INGRESOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '4.2' },
  { codigo: '4.2.02', nombre: 'Otros ingresos', nivel: 3, tipo: 'INGRESOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '4.2' },
  { codigo: '5', nombre: 'GASTOS', nivel: 1, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: null },
  { codigo: '5.1', nombre: 'GASTOS OPERACIONALES', nivel: 2, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '5' },
  { codigo: '5.1.01', nombre: 'Compras', nivel: 3, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.1' },
  { codigo: '5.1.01.01', nombre: 'Compras 12%', nivel: 4, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.1.01' },
  { codigo: '5.1.01.02', nombre: 'Compras 14%', nivel: 4, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.1.01' },
  { codigo: '5.1.01.03', nombre: 'Compras 15%', nivel: 4, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.1.01' },
  { codigo: '5.1.01.04', nombre: 'Compras 0%', nivel: 4, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.1.01' },
  { codigo: '5.1.02', nombre: 'Devolucion en compras', nivel: 3, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.1' },
  { codigo: '5.1.03', nombre: 'Gastos administrativos', nivel: 3, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.1' },
  { codigo: '5.1.04', nombre: 'Gastos de ventas', nivel: 3, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.1' },
  { codigo: '5.1.05', nombre: 'Gastos financieros', nivel: 3, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.1' },
  { codigo: '5.1.06', nombre: 'Sueldos y salarios', nivel: 3, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.1' },
  { codigo: '5.1.07', nombre: 'Beneficios sociales', nivel: 3, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.1' },
  { codigo: '5.1.08', nombre: 'Honorarios profesionales', nivel: 3, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.1' },
  { codigo: '5.1.09', nombre: 'Arriendos', nivel: 3, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.1' },
  { codigo: '5.1.10', nombre: 'Publicidad y propaganda', nivel: 3, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.1' },
  { codigo: '5.1.11', nombre: 'Seguros', nivel: 3, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.1' },
  { codigo: '5.1.12', nombre: 'Servicios basicos', nivel: 3, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.1' },
  { codigo: '5.1.13', nombre: 'Mantenimiento y reparaciones', nivel: 3, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.1' },
  { codigo: '5.1.14', nombre: 'Suministros y materiales', nivel: 3, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.1' },
  { codigo: '5.1.15', nombre: 'Depreciaciones', nivel: 3, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.1' },
  { codigo: '5.1.16', nombre: 'Amortizaciones', nivel: 3, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.1' },
  { codigo: '5.2', nombre: 'GASTOS NO OPERACIONALES', nivel: 2, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '5' },
  { codigo: '5.2.01', nombre: 'Gastos no operacionales', nivel: 3, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.2' },
  { codigo: '5.2.02', nombre: 'Perdida en venta de activos', nivel: 3, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.2' },
  { codigo: '5.3', nombre: 'GASTOS TRIBUTARIOS', nivel: 2, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: false, cuentaPadreCodigo: '5' },
  { codigo: '5.3.01', nombre: 'IVA Gasto', nivel: 3, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.3' },
  { codigo: '5.3.02', nombre: 'Gastos no deducibles', nivel: 3, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.3' },
  { codigo: '5.3.03', nombre: 'Multas e intereses tributarios', nivel: 3, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.3' },
  { codigo: '5.3.04', nombre: 'Impuestos municipales', nivel: 3, tipo: 'GASTOS', esAuxiliar: false, permiteMovimiento: true, cuentaPadreCodigo: '5.3' },
]
